version: '3'

services:
  ayomi_website:
    build: .
    command: bash -c "cd ayomi && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: ayomi
    volumes: 
      - .:/ayomi
    ports:
      - "8000:8000"